services:
  backend:
    build: .
    container_name: ecomerce-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecomerce
      - SPRING_DATASOURCE_USERNAME=david
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AZURE_COMMUNICATION_CONNECTION_STRING=${AZURE_COMMUNICATION_CONNECTION_STRING}
      - AZURE_SENDER_ADDRESS=${AZURE_SENDER_ADDRESS}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_MAX_FILE_SIZE=${STORAGE_MAX_FILE_SIZE}
      - STORAGE_MAX_FILES_COUNT=${STORAGE_MAX_FILES_COUNT}
      - STORAGE_MAX_TOTAL_SIZE=${STORAGE_MAX_TOTAL_SIZE}
      - STORAGE_ALLOWED_CONTENT_TYPES=${STORAGE_ALLOWED_CONTENT_TYPES}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;}
    depends_on:
      - db
    networks:
      - ecomerce-network

  db:
    image: postgres:16-alpine
    container_name: ecomerce-db
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=ecomerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecomerce-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: ecomerce-azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
    networks:
      - ecomerce-network

networks:
  ecomerce-network:
    driver: bridge

volumes:
  db_data:
  azurite_data:
